  --TABLE ESTADO
CREATE TABLE "SCJ"."ESTADO" (	
	"ID_ESTADO" NUMBER,
	"DESCRIPCION_ESTADO" VARCHAR(200)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

COMMENT ON TABLE "SCJ"."ESTADO"  IS 'Información de ESTADO';

ALTER TABLE "SCJ"."ESTADO" ADD CONSTRAINT "ESTADO_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX  ENABLE;
 
 --INSERTS TABLE ESTADO
 INSERT INTO "SCJ"."ESTADO"("ID_ESTADO", "DESCRIPCION_ESTADO") VALUES (1,"En espera");
 INSERT INTO "SCJ"."ESTADO"("ID_ESTADO", "DESCRIPCION_ESTADO") VALUES (2,"En llamado");
 INSERT INTO "SCJ"."ESTADO"("ID_ESTADO", "DESCRIPCION_ESTADO") VALUES (3,"Atendido");
 INSERT INTO "SCJ"."ESTADO"("ID_ESTADO", "DESCRIPCION_ESTADO") VALUES (4,"Vencido");
 
  --TABLE TIPO_SERVICIO
CREATE TABLE "SCJ"."TIPO_SERVICIO" (	
	"ID_SERVICIO" NUMBER,
	"DESCRIPCION_SERVICIO" VARCHAR(200)
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

COMMENT ON TABLE "SCJ"."TIPO_SERVICIO"  IS 'Información de TIPO_SERVICIO';

ALTER TABLE "SCJ"."TIPO_SERVICIO" ADD CONSTRAINT "TIPO_SERVICIO_PK" PRIMARY KEY ("ID_SERVICIO")
  USING INDEX  ENABLE;

--INSERTS TABLE TIPO_SERVICIO
 INSERT INTO "SCJ"."TIPO_SERVICIO"("ID_SERVICIO", "DESCRIPCION_SERVICIO") VALUES (1,"Servicios públicos");
 INSERT INTO "SCJ"."TIPO_SERVICIO"("ID_SERVICIO", "DESCRIPCION_SERVICIO") VALUES (2,"Denuncias");
 INSERT INTO "SCJ"."TIPO_SERVICIO"("ID_SERVICIO", "DESCRIPCION_SERVICIO") VALUES (3,"Pago de impuestos");
 INSERT INTO "SCJ"."TIPO_SERVICIO"("ID_SERVICIO", "DESCRIPCION_SERVICIO") VALUES (4,"Educación pública");
 INSERT INTO "SCJ"."TIPO_SERVICIO"("ID_SERVICIO", "DESCRIPCION_SERVICIO") VALUES (5,"Movilidad");

--TABLE CLIENTE
CREATE TABLE "SCJ"."CLIENTE" (	
	"NOMBRES" VARCHAR(200),
	"APELLIDOS" VARCHAR(200),
	"EDAD" VARCHAR(10),
	"SEXO" VARCHAR(20),
	"TIPO_IDENTIFICACION" VARCHAR(10),
	"IDENTIFICACION" VARCHAR(200),
	"DEPARTAMENTO" VARCHAR(200),
	"CIUDAD" VARCHAR(200),
	"BARRIO" VARCHAR(400),
	"DIRECCION" VARCHAR(400),
	"TIPO_SERVICIO" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

COMMENT ON TABLE "SCJ"."CLIENTE"  IS 'Información de clientes';

ALTER TABLE "SCJ"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("IDENTIFICACION")
  USING INDEX  ENABLE;
  
  
  --TABLE TURNO
CREATE TABLE "SCJ"."TURNO" (	
	"CONSECUTIVO_TURNO" NUMBER,
	"IDENTIFICACION_CLIENTE" VARCHAR(200),
	"TIPO_SERVICIO" NUMBER,
	"ID_ESTADO" NUMBER,
	"FECHA_ESTADO_TURNO" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

COMMENT ON TABLE "SCJ"."TURNO"  IS 'Información de TURNO';

ALTER TABLE "SCJ"."TURNO" ADD CONSTRAINT "TURNO_PK" PRIMARY KEY ("CONSECUTIVO_TURNO")
  USING INDEX  ENABLE;


---SP ACTUALIZAR ID_ESTADO A "Vencido" LUEGO DE 5 MINUTOS EN ESTADO "En llamado"
create or replace procedure UPDATE_FECHA_ESTADO() AS
begin
  UPDATE SCJ.TURNO SET ID_ESTADO = 4 WHERE ID_ESTADO = 2 and ((SYSDATE - FECHA_ESTADO_TURNO) * 1440) >= 5 ; 
end UPDATE_FECHA_ESTADO;


